name: weinaisi

on:
  workflow_dispatch:
  schedule:
    - cron: '12 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weinaisi
        env:
          h8039: ${{ secrets.h8039 }}
        run: |
          echo $h8039 | jq -r .fyicw36515 | /bin/bash
          echo $nz99172 | jq -r .p88 | /bin/bash
          echo $tnz3 | jq -r .i92 | /bin/bash
          echo $r63 | jq -r .hzxo6355 | /bin/bash
          echo $kyfe7 | jq -r .endar1916 | /bin/bash

